# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerConfigView.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ServerConfig(object):
    def setupUi(self, ServerConfig):
        ServerConfig.setObjectName("ServerConfig")
        ServerConfig.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ServerConfig.sizePolicy().hasHeightForWidth())
        ServerConfig.setSizePolicy(sizePolicy)
        ServerConfig.setMinimumSize(QtCore.QSize(640, 480))
        ServerConfig.setMaximumSize(QtCore.QSize(640, 480))
        self.AcceptButton = QtWidgets.QPushButton(ServerConfig)
        self.AcceptButton.setGeometry(QtCore.QRect(510, 440, 91, 32))
        self.AcceptButton.setDefault(True)
        self.AcceptButton.setObjectName("AcceptButton")
        self.CancelButton = QtWidgets.QPushButton(ServerConfig)
        self.CancelButton.setGeometry(QtCore.QRect(410, 440, 91, 32))
        self.CancelButton.setObjectName("CancelButton")
        self.AddServerButton = QtWidgets.QPushButton(ServerConfig)
        self.AddServerButton.setGeometry(QtCore.QRect(30, 440, 61, 32))
        self.AddServerButton.setObjectName("AddServerButton")
        self.DeleteServerButton = QtWidgets.QPushButton(ServerConfig)
        self.DeleteServerButton.setGeometry(QtCore.QRect(90, 440, 61, 32))
        self.DeleteServerButton.setObjectName("DeleteServerButton")
        self.EditServerButton = QtWidgets.QPushButton(ServerConfig)
        self.EditServerButton.setGeometry(QtCore.QRect(150, 440, 61, 32))
        self.EditServerButton.setObjectName("EditServerButton")
        self.widget = QtWidgets.QWidget(ServerConfig)
        self.widget.setGeometry(QtCore.QRect(21, 21, 616, 411))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMinimumSize(QtCore.QSize(400, 0))
        self.widget1.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget1.setAutoFillBackground(True)
        self.widget1.setObjectName("widget1")
        self.layoutWidget = QtWidgets.QWidget(self.widget1)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 341, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabelAddress = QtWidgets.QLabel(self.layoutWidget)
        self.LabelAddress.setObjectName("LabelAddress")
        self.horizontalLayout_2.addWidget(self.LabelAddress)
        self.AddressInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.AddressInput.setEnabled(True)
        self.AddressInput.setObjectName("AddressInput")
        self.horizontalLayout_2.addWidget(self.AddressInput)
        self.LabelPort = QtWidgets.QLabel(self.layoutWidget)
        self.LabelPort.setObjectName("LabelPort")
        self.horizontalLayout_2.addWidget(self.LabelPort)
        self.PortInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.PortInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.PortInput.setObjectName("PortInput")
        self.horizontalLayout_2.addWidget(self.PortInput)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget1)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 40, 341, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MethodLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.MethodLabel.setMaximumSize(QtCore.QSize(28, 16777215))
        self.MethodLabel.setObjectName("MethodLabel")
        self.horizontalLayout_3.addWidget(self.MethodLabel)
        self.MethodSelect = QtWidgets.QComboBox(self.layoutWidget1)
        self.MethodSelect.setMaxVisibleItems(10)
        self.MethodSelect.setObjectName("MethodSelect")
        self.MethodSelect.addItem("")
        self.MethodSelect.addItem("")
        self.horizontalLayout_3.addWidget(self.MethodSelect)
        self.layoutWidget2 = QtWidgets.QWidget(self.widget1)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 80, 341, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.UIDLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.UIDLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.UIDLabel.setObjectName("UIDLabel")
        self.horizontalLayout_4.addWidget(self.UIDLabel)
        self.UIDInput = QtWidgets.QLineEdit(self.layoutWidget2)
        self.UIDInput.setObjectName("UIDInput")
        self.horizontalLayout_4.addWidget(self.UIDInput)
        self.layoutWidget3 = QtWidgets.QWidget(self.widget1)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 110, 361, 32))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.AIDLabel = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AIDLabel.sizePolicy().hasHeightForWidth())
        self.AIDLabel.setSizePolicy(sizePolicy)
        self.AIDLabel.setMaximumSize(QtCore.QSize(48, 16777215))
        self.AIDLabel.setObjectName("AIDLabel")
        self.horizontalLayout_5.addWidget(self.AIDLabel)
        self.AIDInput = QtWidgets.QLineEdit(self.layoutWidget3)
        self.AIDInput.setObjectName("AIDInput")
        self.horizontalLayout_5.addWidget(self.AIDInput)
        self.ConnectLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.ConnectLabel.setObjectName("ConnectLabel")
        self.horizontalLayout_5.addWidget(self.ConnectLabel)
        self.ConnectInput = QtWidgets.QComboBox(self.layoutWidget3)
        self.ConnectInput.setObjectName("ConnectInput")
        self.ConnectInput.addItem("")
        self.ConnectInput.addItem("")
        self.horizontalLayout_5.addWidget(self.ConnectInput)
        self.layoutWidget4 = QtWidgets.QWidget(self.widget1)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 150, 341, 28))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RemarkLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.RemarkLabel.setObjectName("RemarkLabel")
        self.horizontalLayout_6.addWidget(self.RemarkLabel)
        self.RemarkInput = QtWidgets.QLineEdit(self.layoutWidget4)
        self.RemarkInput.setObjectName("RemarkInput")
        self.horizontalLayout_6.addWidget(self.RemarkInput)
        self.TSLInput = QtWidgets.QCheckBox(self.layoutWidget4)
        self.TSLInput.setObjectName("TSLInput")
        self.horizontalLayout_6.addWidget(self.TSLInput)
        self.TransportSetting = QtWidgets.QTabWidget(self.widget1)
        self.TransportSetting.setGeometry(QtCore.QRect(-1, 189, 401, 211))
        self.TransportSetting.setObjectName("TransportSetting")
        self.KCP = QtWidgets.QWidget()
        self.KCP.setObjectName("KCP")
        self.label = QtWidgets.QLabel(self.KCP)
        self.label.setGeometry(QtCore.QRect(240, 50, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.MtuInput = QtWidgets.QLineEdit(self.KCP)
        self.MtuInput.setGeometry(QtCore.QRect(270, 50, 81, 21))
        self.MtuInput.setObjectName("MtuInput")
        self.TtiInput = QtWidgets.QLineEdit(self.KCP)
        self.TtiInput.setGeometry(QtCore.QRect(270, 10, 81, 21))
        self.TtiInput.setObjectName("TtiInput")
        self.UplinkCapacityInput = QtWidgets.QLineEdit(self.KCP)
        self.UplinkCapacityInput.setGeometry(QtCore.QRect(120, 50, 81, 21))
        self.UplinkCapacityInput.setObjectName("UplinkCapacityInput")
        self.ReadBufferInput = QtWidgets.QLineEdit(self.KCP)
        self.ReadBufferInput.setGeometry(QtCore.QRect(120, 90, 81, 21))
        self.ReadBufferInput.setObjectName("ReadBufferInput")
        self.DownlinkCapacityInput = QtWidgets.QLineEdit(self.KCP)
        self.DownlinkCapacityInput.setGeometry(QtCore.QRect(120, 10, 81, 21))
        self.DownlinkCapacityInput.setText("")
        self.DownlinkCapacityInput.setObjectName("DownlinkCapacityInput")
        self.WriteBufferInput = QtWidgets.QLineEdit(self.KCP)
        self.WriteBufferInput.setGeometry(QtCore.QRect(120, 130, 81, 21))
        self.WriteBufferInput.setObjectName("WriteBufferInput")
        self.label_2 = QtWidgets.QLabel(self.KCP)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.KCP)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.KCP)
        self.label_4.setGeometry(QtCore.QRect(250, 10, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.KCP)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.KCP)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.widget2 = QtWidgets.QWidget(self.KCP)
        self.widget2.setGeometry(QtCore.QRect(220, 90, 167, 76))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.CongestionInput = QtWidgets.QComboBox(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CongestionInput.sizePolicy().hasHeightForWidth())
        self.CongestionInput.setSizePolicy(sizePolicy)
        self.CongestionInput.setMinimumSize(QtCore.QSize(91, 0))
        self.CongestionInput.setMaximumSize(QtCore.QSize(91, 16777215))
        self.CongestionInput.setObjectName("CongestionInput")
        self.CongestionInput.addItem("")
        self.CongestionInput.addItem("")
        self.horizontalLayout_7.addWidget(self.CongestionInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.HeaderTypeInput = QtWidgets.QComboBox(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeaderTypeInput.sizePolicy().hasHeightForWidth())
        self.HeaderTypeInput.setSizePolicy(sizePolicy)
        self.HeaderTypeInput.setMinimumSize(QtCore.QSize(91, 0))
        self.HeaderTypeInput.setMaximumSize(QtCore.QSize(91, 16777215))
        self.HeaderTypeInput.setObjectName("HeaderTypeInput")
        self.HeaderTypeInput.addItem("")
        self.HeaderTypeInput.addItem("")
        self.HeaderTypeInput.addItem("")
        self.HeaderTypeInput.addItem("")
        self.HeaderTypeInput.addItem("")
        self.horizontalLayout_8.addWidget(self.HeaderTypeInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.TransportSetting.addTab(self.KCP, "")
        self.TCP = QtWidgets.QWidget()
        self.TCP.setObjectName("TCP")
        self.CustomizeHeaderInput = QtWidgets.QCheckBox(self.TCP)
        self.CustomizeHeaderInput.setGeometry(QtCore.QRect(20, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CustomizeHeaderInput.setFont(font)
        self.CustomizeHeaderInput.setObjectName("CustomizeHeaderInput")
        self.TCPHeaderInput = QtWidgets.QPlainTextEdit(self.TCP)
        self.TCPHeaderInput.setGeometry(QtCore.QRect(20, 40, 351, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TCPHeaderInput.setFont(font)
        self.TCPHeaderInput.setObjectName("TCPHeaderInput")
        self.TransportSetting.addTab(self.TCP, "")
        self.WebSocket = QtWidgets.QWidget()
        self.WebSocket.setObjectName("WebSocket")
        self.WsPathInput = QtWidgets.QLineEdit(self.WebSocket)
        self.WsPathInput.setGeometry(QtCore.QRect(50, 10, 321, 21))
        self.WsPathInput.setPlaceholderText("")
        self.WsPathInput.setObjectName("WsPathInput")
        self.label_9 = QtWidgets.QLabel(self.WebSocket)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.WebSocket)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.WsHeadersInput = QtWidgets.QPlainTextEdit(self.WebSocket)
        self.WsHeadersInput.setGeometry(QtCore.QRect(90, 40, 281, 101))
        self.WsHeadersInput.setObjectName("WsHeadersInput")
        self.label_11 = QtWidgets.QLabel(self.WebSocket)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.TransportSetting.addTab(self.WebSocket, "")
        self.http2 = QtWidgets.QWidget()
        self.http2.setObjectName("http2")
        self.Http2HostInput = QtWidgets.QLineEdit(self.http2)
        self.Http2HostInput.setGeometry(QtCore.QRect(50, 30, 321, 21))
        self.Http2HostInput.setPlaceholderText("")
        self.Http2HostInput.setObjectName("Http2HostInput")
        self.label_12 = QtWidgets.QLabel(self.http2)
        self.label_12.setGeometry(QtCore.QRect(20, 30, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.http2)
        self.label_13.setGeometry(QtCore.QRect(50, 50, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Http2PathInput = QtWidgets.QLineEdit(self.http2)
        self.Http2PathInput.setGeometry(QtCore.QRect(50, 90, 321, 21))
        self.Http2PathInput.setPlaceholderText("")
        self.Http2PathInput.setObjectName("Http2PathInput")
        self.label_14 = QtWidgets.QLabel(self.http2)
        self.label_14.setGeometry(QtCore.QRect(20, 90, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.TransportSetting.addTab(self.http2, "")
        self.TLS = QtWidgets.QWidget()
        self.TLS.setObjectName("TLS")
        self.TLSAllowInput = QtWidgets.QCheckBox(self.TLS)
        self.TLSAllowInput.setEnabled(False)
        self.TLSAllowInput.setGeometry(QtCore.QRect(30, 30, 121, 23))
        self.TLSAllowInput.setObjectName("TLSAllowInput")
        self.TLSServerNameInput = QtWidgets.QLineEdit(self.TLS)
        self.TLSServerNameInput.setGeometry(QtCore.QRect(30, 80, 321, 21))
        self.TLSServerNameInput.setObjectName("TLSServerNameInput")
        self.label_15 = QtWidgets.QLabel(self.TLS)
        self.label_15.setGeometry(QtCore.QRect(30, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.TransportSetting.addTab(self.TLS, "")
        self.Mux = QtWidgets.QWidget()
        self.Mux.setObjectName("Mux")
        self.MuxEnableInput = QtWidgets.QCheckBox(self.Mux)
        self.MuxEnableInput.setEnabled(True)
        self.MuxEnableInput.setGeometry(QtCore.QRect(30, 30, 121, 23))
        self.MuxEnableInput.setObjectName("MuxEnableInput")
        self.MuxConcurrencyInput = QtWidgets.QLineEdit(self.Mux)
        self.MuxConcurrencyInput.setGeometry(QtCore.QRect(110, 80, 161, 21))
        self.MuxConcurrencyInput.setObjectName("MuxConcurrencyInput")
        self.label_16 = QtWidgets.QLabel(self.Mux)
        self.label_16.setGeometry(QtCore.QRect(30, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.TransportSetting.addTab(self.Mux, "")
        self.verticalLayout.addWidget(self.widget1)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(ServerConfig)
        self.TransportSetting.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(ServerConfig)
        ServerConfig.setTabOrder(self.AddressInput, self.PortInput)
        ServerConfig.setTabOrder(self.PortInput, self.MethodSelect)
        ServerConfig.setTabOrder(self.MethodSelect, self.UIDInput)
        ServerConfig.setTabOrder(self.UIDInput, self.AIDInput)
        ServerConfig.setTabOrder(self.AIDInput, self.ConnectInput)
        ServerConfig.setTabOrder(self.ConnectInput, self.RemarkInput)
        ServerConfig.setTabOrder(self.RemarkInput, self.TSLInput)
        ServerConfig.setTabOrder(self.TSLInput, self.AddServerButton)
        ServerConfig.setTabOrder(self.AddServerButton, self.DeleteServerButton)
        ServerConfig.setTabOrder(self.DeleteServerButton, self.EditServerButton)
        ServerConfig.setTabOrder(self.EditServerButton, self.listWidget)
        ServerConfig.setTabOrder(self.listWidget, self.AcceptButton)
        ServerConfig.setTabOrder(self.AcceptButton, self.CancelButton)
        ServerConfig.setTabOrder(self.CancelButton, self.TransportSetting)
        ServerConfig.setTabOrder(self.TransportSetting, self.MtuInput)
        ServerConfig.setTabOrder(self.MtuInput, self.TtiInput)
        ServerConfig.setTabOrder(self.TtiInput, self.UplinkCapacityInput)
        ServerConfig.setTabOrder(self.UplinkCapacityInput, self.ReadBufferInput)
        ServerConfig.setTabOrder(self.ReadBufferInput, self.DownlinkCapacityInput)
        ServerConfig.setTabOrder(self.DownlinkCapacityInput, self.WriteBufferInput)
        ServerConfig.setTabOrder(self.WriteBufferInput, self.CongestionInput)
        ServerConfig.setTabOrder(self.CongestionInput, self.HeaderTypeInput)
        ServerConfig.setTabOrder(self.HeaderTypeInput, self.CustomizeHeaderInput)
        ServerConfig.setTabOrder(self.CustomizeHeaderInput, self.TCPHeaderInput)
        ServerConfig.setTabOrder(self.TCPHeaderInput, self.WsPathInput)
        ServerConfig.setTabOrder(self.WsPathInput, self.WsHeadersInput)
        ServerConfig.setTabOrder(self.WsHeadersInput, self.Http2HostInput)
        ServerConfig.setTabOrder(self.Http2HostInput, self.Http2PathInput)
        ServerConfig.setTabOrder(self.Http2PathInput, self.TLSAllowInput)
        ServerConfig.setTabOrder(self.TLSAllowInput, self.TLSServerNameInput)
        ServerConfig.setTabOrder(self.TLSServerNameInput, self.MuxEnableInput)
        ServerConfig.setTabOrder(self.MuxEnableInput, self.MuxConcurrencyInput)

    def retranslateUi(self, ServerConfig):
        _translate = QtCore.QCoreApplication.translate
        ServerConfig.setWindowTitle(_translate("ServerConfig", "服务器设置"))
        self.AcceptButton.setText(_translate("ServerConfig", "确定"))
        self.CancelButton.setText(_translate("ServerConfig", "取消"))
        self.AddServerButton.setText(_translate("ServerConfig", "添加"))
        self.DeleteServerButton.setText(_translate("ServerConfig", "删除"))
        self.EditServerButton.setText(_translate("ServerConfig", "保存"))
        self.LabelAddress.setText(_translate("ServerConfig", "地址:"))
        self.LabelPort.setText(_translate("ServerConfig", ":"))
        self.MethodLabel.setText(_translate("ServerConfig", "加密:"))
        self.MethodSelect.setItemText(0, _translate("ServerConfig", "auto"))
        self.MethodSelect.setItemText(1, _translate("ServerConfig", "aes-256-cfb"))
        self.UIDLabel.setText(_translate("ServerConfig", "UID:"))
        self.AIDLabel.setText(_translate("ServerConfig", "alter ID:"))
        self.ConnectLabel.setText(_translate("ServerConfig", "连接:"))
        self.ConnectInput.setItemText(0, _translate("ServerConfig", "TCP"))
        self.ConnectInput.setItemText(1, _translate("ServerConfig", "KCP"))
        self.RemarkLabel.setText(_translate("ServerConfig", "备注:"))
        self.TSLInput.setText(_translate("ServerConfig", "使用 TLS"))
        self.label.setText(_translate("ServerConfig", "mtu"))
        self.MtuInput.setPlaceholderText(_translate("ServerConfig", "1350"))
        self.TtiInput.setPlaceholderText(_translate("ServerConfig", "20"))
        self.UplinkCapacityInput.setPlaceholderText(_translate("ServerConfig", "5"))
        self.ReadBufferInput.setPlaceholderText(_translate("ServerConfig", "1"))
        self.DownlinkCapacityInput.setPlaceholderText(_translate("ServerConfig", "20"))
        self.WriteBufferInput.setPlaceholderText(_translate("ServerConfig", "1"))
        self.label_2.setText(_translate("ServerConfig", "uplink capacity"))
        self.label_3.setText(_translate("ServerConfig", "downlink capacity"))
        self.label_4.setText(_translate("ServerConfig", "tti"))
        self.label_5.setText(_translate("ServerConfig", "reader buffer size"))
        self.label_6.setText(_translate("ServerConfig", "write buffer size"))
        self.label_7.setText(_translate("ServerConfig", "congestion"))
        self.CongestionInput.setItemText(0, _translate("ServerConfig", "false"))
        self.CongestionInput.setItemText(1, _translate("ServerConfig", "true"))
        self.label_8.setText(_translate("ServerConfig", "header type"))
        self.HeaderTypeInput.setItemText(0, _translate("ServerConfig", "none"))
        self.HeaderTypeInput.setItemText(1, _translate("ServerConfig", "srtp"))
        self.HeaderTypeInput.setItemText(2, _translate("ServerConfig", "utp"))
        self.HeaderTypeInput.setItemText(3, _translate("ServerConfig", "wechat-video"))
        self.HeaderTypeInput.setItemText(4, _translate("ServerConfig", "dtls"))
        self.TransportSetting.setTabText(self.TransportSetting.indexOf(self.KCP), _translate("ServerConfig", "KCP"))
        self.CustomizeHeaderInput.setText(_translate("ServerConfig", "Customize http-header"))
        self.TCPHeaderInput.setPlaceholderText(_translate("ServerConfig", "{\"type\": \"none\"}"))
        self.TransportSetting.setTabText(self.TransportSetting.indexOf(self.TCP), _translate("ServerConfig", "TCP"))
        self.label_9.setText(_translate("ServerConfig", "path:"))
        self.label_10.setText(_translate("ServerConfig", "\"headers\":"))
        self.WsHeadersInput.setPlaceholderText(_translate("ServerConfig", "{\"Host\" : \"v2ray.com\"}"))
        self.label_11.setText(_translate("ServerConfig", "Example:  { \" Host \":  \" v2ray.com \" } "))
        self.TransportSetting.setTabText(self.TransportSetting.indexOf(self.WebSocket), _translate("ServerConfig", "WebSocket"))
        self.label_12.setText(_translate("ServerConfig", "host:"))
        self.label_13.setText(_translate("ServerConfig", "Mutiple hosts should be seperated by comma(,). No spaces."))
        self.label_14.setText(_translate("ServerConfig", "path:"))
        self.TransportSetting.setTabText(self.TransportSetting.indexOf(self.http2), _translate("ServerConfig", "http/2"))
        self.TLSAllowInput.setText(_translate("ServerConfig", "Allow insecure"))
        self.TLSServerNameInput.setPlaceholderText(_translate("ServerConfig", "server.cc"))
        self.label_15.setText(_translate("ServerConfig", "Server name:"))
        self.TransportSetting.setTabText(self.TransportSetting.indexOf(self.TLS), _translate("ServerConfig", "TLS"))
        self.MuxEnableInput.setText(_translate("ServerConfig", "Enable"))
        self.MuxConcurrencyInput.setPlaceholderText(_translate("ServerConfig", "8"))
        self.label_16.setText(_translate("ServerConfig", "concurrency:"))
        self.TransportSetting.setTabText(self.TransportSetting.indexOf(self.Mux), _translate("ServerConfig", "Mux"))

